=== alakim/xmlbrainstorm/defs/brainstorm.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % basicMarkup "#PCDATA | p | ref | list">
<!ELEMENT brainstorm (problem)*>
<!ATTLIST brainstorm
	title CDATA #REQUIRED
>
<!ELEMENT problem (description?, (problem | solution)*)>
<!ATTLIST problem
	id ID #IMPLIED
	title CDATA #REQUIRED
>
<!ELEMENT solution (description?, advantage*, disadvantage*, problem*)>
<!ATTLIST solution
	id ID #IMPLIED
	title CDATA #REQUIRED
	rate (-3 | -2 | -1 | 0 | 1 | 2 | 3) "0"
>
<!ELEMENT description (%basicMarkup;)*>
<!ELEMENT p (#PCDATA | ref)*>
<!ELEMENT ref EMPTY>
<!ATTLIST ref
	id IDREF #REQUIRED
>
<!ELEMENT advantage (%basicMarkup;)*>
<!ATTLIST advantage
	rate (1 | 2 | 3) "1"
>
<!ELEMENT disadvantage (%basicMarkup;)*>
<!ATTLIST disadvantage
	rate (1 | 2 | 3) "1"
>
<!ELEMENT list (li)*>
<!ELEMENT li (#PCDATA | ref)*>

=== alakim/xmlbrainstorm/trunk/decisionSample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE brainstorm SYSTEM "defs/brainstorm.dtd">
<?xml-stylesheet type="text/xsl" href="defs/brainstorm.xslt"?>
<brainstorm title="Пример принятия решения">
	<problem title="Стоит ли развивать этот проект?">
		<description>Найдет ли этот проект хоть какое-то применение?</description>
		<solution title="Надо развивать">
			<advantage>Пригодится когда-нибудь</advantage>
			<disadvantage>Да сколько уже таких проектов было!</disadvantage>
			<problem title="Время и другие ресурсы">
				<description>Проект-то хоть и небольшой, однако, трудоемкость какая-никакая, все-таки имеется.</description>
			</problem>
		</solution>
		<solution title="Забросить, и больше не вспоминать">
			<advantage>Нет проекта - нет и проблем!</advantage>
		</solution>
	</problem>
</brainstorm>
